name: CI (migrated from Travis)

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  DEBUG: "true"
  TRAVIS_BUILD_DIR: ${{ github.workspace }}

jobs:
  php84-mysql:
    name: "PHP 8.4 + MySQL (runs on push & PR)"
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-22.04

    # Run all shell steps from inside the Dolibarr tree
    defaults:
      run:
        working-directory: dolibarr

    env:
      DB: mysql
      TRAVIS_PHP_VERSION: "8.4"
      # Point TRAVIS_BUILD_DIR at the Dolibarr checkout (not repo root)
      TRAVIS_BUILD_DIR: ${{ github.workspace }}/dolibarr

    steps:
      # 1) Checkout Dolibarr v22.x (branch 22.0).
      - uses: actions/checkout@v4
        with:
          repository: Dolibarr/dolibarr
          ref: "22.0"            # or use the exact tag e.g. "refs/tags/22.0.0"
          fetch-depth: 0
          path: dolibarr

      - uses: actions/checkout@v4
        with:
          path: dolibarr/htdocs/custom/${{ github.event.repository.name }}

      - uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-${{ runner.os }}-${{ env.TRAVIS_PHP_VERSION }}

      - name: Before install — PPA + apt update
        run: |
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update
          echo TRAVIS_PHP_VERSION=$TRAVIS_PHP_VERSION

      - name: Install PHP 8.4 + Apache + tools (memcached, pgloader)
        run: |
          sudo apt-get install -y pgloader memcached
          sudo apt install -y unzip apache2 php8.4 php8.4-cli php8.4-curl php8.4-mysql php8.4-pgsql php8.4-gd php8.4-imap php8.4-intl php8.4-ldap php8.4-xml php8.4-mbstring php8.4-zip libapache2-mod-php8.4

      - name: MySQL init (mirror Travis)
        run: |
          sudo apt-get install -y mariadb-server
          sudo systemctl stop mariadb.service || true
          sudo mysqld_safe --skip-grant-tables --socket=/tmp/aaa &
          sleep 3
          sudo mysql -u root -h 127.0.0.1 -e "FLUSH PRIVILEGES; CREATE DATABASE IF NOT EXISTS travis CHARACTER SET = 'utf8'; ALTER USER 'root'@'localhost' IDENTIFIED BY 'password'; CREATE USER 'root'@'127.0.0.1' IDENTIFIED BY 'password'; CREATE USER 'travis'@'127.0.0.1' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON travis.* TO root@127.0.0.1; GRANT ALL PRIVILEGES ON travis.* TO travis@127.0.0.1; FLUSH PRIVILEGES;"
          sudo mysql -u root -h 127.0.0.1 -ppassword -e 'GRANT ALL PRIVILEGES ON travis.* TO travis@127.0.0.1; FLUSH PRIVILEGES;'
          sudo mysql -u root -h 127.0.0.1 -ppassword -D travis < dev/initdemo/mysqldump_dolibarr_3.5.0.sql

      - name: Install — select PHP, Composer, dependencies
        run: |
          sudo update-alternatives --set php /usr/bin/php8.4
          php -i | head -
          curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
          HASH=$(curl -sS https://composer.github.io/installer.sig)
          php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('/tmp/composer-setup.php'); } echo PHP_EOL;"
          sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
          sudo chmod -R a+rwx /usr/local/bin/composer
          composer -V
          sudo composer -n config -g vendor-dir htdocs/includes
          sudo chmod -R a+rwx $HOME/.config/composer

          sudo composer self-update 2.4.4
          composer -n require --ignore-platform-reqs phpunit/phpunit ^8 \
                                                     php-parallel-lint/php-parallel-lint ^1.2 \
                                                     php-parallel-lint/php-console-highlighter ^0 \
                                                     php-parallel-lint/php-var-dump-check ~0.4 \
                                                     squizlabs/php_codesniffer ^3

          # Add Dolibarr composer bin dir to PATH
          echo "${TRAVIS_BUILD_DIR}/htdocs/includes/bin" >> "$GITHUB_PATH"

      - name: before_script — env + versions
        run: |
          echo Start before_script
          echo "pwd=$(pwd)"
          echo "HOME=$HOME"
          echo "TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR"

          echo "Versions information"
          echo "PHP version"
          php -i | head -
          echo "Parallel-lint version"
          which parallel-lint
          parallel-lint -V
          echo "PHPCS version"
          which phpcs
          phpcs --version | head -
          phpcs -i | head -
          echo "PHP Vardump check version"
          which var-dump-check
          var-dump-check --version
          echo "PHPUnit version"
          which phpunit
          phpunit --version | head -
          echo "Apache version"
          apache2 -v | head - || true
          echo "Database version"
          mysql --version | head - || true
          psql --version || true

      - name: Create Dolibarr conf, documents, Apache vhost
        run: |
          export CONF_FILE=htdocs/conf/conf.php
          echo "Setting up Dolibarr '$CONF_FILE'"
          {
            echo '<?php'
            echo 'error_reporting(E_ALL);'
            echo '$dolibarr_main_url_root=\'http://127.0.0.1\';'
            echo '$dolibarr_main_document_root='\'''"$TRAVIS_BUILD_DIR"'/htdocs'\'';'
            echo '$dolibarr_main_data_root='\'''"$TRAVIS_BUILD_DIR"'/documents'\'';'
            echo '$dolibarr_main_db_host=\'127.0.0.1\';'
            echo '$dolibarr_main_db_name=\'travis\';'
            echo '$dolibarr_main_instance_unique_id=\'travis1234567890\';'
            echo '$dolibarr_main_db_type=\'mysqli\';'
            echo '$dolibarr_main_db_port=3306;'
            echo '$dolibarr_main_db_user=\'root\';'
            echo '$dolibarr_main_db_pass=\'password\';'
            echo '$dolibarr_main_authentication=\'dolibarr\';'
          } > "$CONF_FILE"
          mkdir -p "$TRAVIS_BUILD_DIR/documents/admin/temp"
          sudo chmod -R a+rwx "$TRAVIS_BUILD_DIR/documents"
          echo "***** First line of dolibarr.log" > "$TRAVIS_BUILD_DIR/documents/dolibarr.log"
          sudo sed -i -e "s,www-data,$USER,g" /etc/apache2/envvars || true
          sudo cp -f dev/build/travis-ci/apache.conf /etc/apache2/sites-available/000-default.conf
          sudo sed -e "s?%TRAVIS_BUILD_DIR%?${TRAVIS_BUILD_DIR}?g" --in-place /etc/apache2/sites-available/000-default.conf
          sudo cat /etc/apache2/sites-available/000-default.conf
          sudo service apache2 restart || true

      - name: Script — webserver check
        run: |
          set +e
          wget -O - --debug http://127.0.0.1 > test.html || true
          head -n 200 test.html || true
          # prefer custom travis_error_log, fall back to default error.log
          sudo cat /var/log/apache2/travis_error_log || sudo tail -n 200 /var/log/apache2/error.log || true

      - name: Lint (8.4)
        run: |
          set -e
          parallel-lint -e php --exclude dev/tools/test/namespacemig --exclude htdocs/includes/composer --exclude htdocs/includes/myclabs --exclude htdocs/includes/phpspec --exclude dev/initdata/dbf/includes \
            --exclude htdocs/includes/sabre --exclude htdocs/includes/phpoffice/PhpSpreadsheet --exclude htdocs/includes/sebastian \
            --exclude htdocs/includes/squizlabs/php_codesniffer --exclude htdocs/includes/jakub-onderka --exclude htdocs/includes/php-parallel-lint --exclude htdocs/includes/symfony \
            --exclude htdocs/includes/mike42/escpos-php/example --exclude htdocs/includes/maximebf \
            --exclude htdocs/includes/phpunit/ --exclude htdocs/includes/tecnickcom/tcpdf/include/barcodes --exclude htdocs/includes/webmozart --exclude htdocs/includes/webklex --blame .
          set +e

      - name: PHPCS (8.4)
        run: |
          set -e
          CACHE_OPT="--cache=${HOME}/.cache/dolibarr-phpcs-${TRAVIS_PHP_VERSION}.cache"
          phpcs -s -p -d memory_limit=-1 --extensions=php --colors --tab-width=4 --standard=dev/setup/codesniffer/ruleset.xml --encoding=utf-8 --severity=1 ${CACHE_OPT} --runtime-set ignore_warnings_on_exit true .
          set +e

      - name: var-dump-check (8.4)
        run: |
          set -e
          var-dump-check --extensions php --tracy --exclude htdocs/includes --exclude test/ --exclude htdocs/public/test/ --exclude htdocs/core/lib/functions.lib.php .
          set +e

      - name: Prepare install.forced.php
        run: |
          export INSTALL_FORCED_FILE=htdocs/install/install.forced.php
          set +e
          {
            echo '<?php '
            echo 'error_reporting(E_ALL);'
            echo '$force_install_noedit=2;'
            echo '$force_install_type=\'mysqli\';'
            echo '$force_install_port=3306;'
            echo '$force_install_dbserver=\'127.0.0.1\';'
            echo '$force_install_database=\'travis\';'
            echo '$force_install_databaselogin=\'travis\';'
            echo '$force_install_databasepass=\'\';'
            echo '$force_install_prefix=\'llx_\';'
            echo '$force_install_createdatabase=false;'
            echo '$force_install_createuser=false;'
            echo '$force_install_mainforcehttps=false;'
            echo '$force_install_main_data_root='\'''"$TRAVIS_BUILD_DIR"'/htdocs'\'';'
          } > "$INSTALL_FORCED_FILE"

      - name: Upgrades chain
        run: |
          set +e
          cd htdocs/install
          php upgrade.php 3.5.0 3.6.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade350360.log
          php upgrade2.php 3.5.0 3.6.0 > $TRAVIS_BUILD_DIR/upgrade350360-2.log
          php step5.php 3.5.0 3.6.0 > $TRAVIS_BUILD_DIR/upgrade350360-3.log
          php upgrade.php 3.6.0 3.7.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade360370.log
          php upgrade2.php 3.6.0 3.7.0 > $TRAVIS_BUILD_DIR/upgrade360370-2.log
          php step5.php 3.6.0 3.7.0 > $TRAVIS_BUILD_DIR/upgrade360370-3.log
          php upgrade.php 3.7.0 3.8.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade370380.log
          php upgrade2.php 3.7.0 3.8.0 > $TRAVIS_BUILD_DIR/upgrade370380-2.log
          php step5.php 3.7.0 3.8.0 > $TRAVIS_BUILD_DIR/upgrade370380-3.log
          php upgrade.php 3.8.0 3.9.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade380390.log
          php upgrade2.php 3.8.0 3.9.0 > $TRAVIS_BUILD_DIR/upgrade380390-2.log
          php step5.php 3.8.0 3.9.0 > $TRAVIS_BUILD_DIR/upgrade380390-3.log
          php upgrade.php 3.9.0 4.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade390400.log
          php upgrade2.php 3.9.0 4.0.0 > $TRAVIS_BUILD_DIR/upgrade390400-2.log
          php step5.php 3.9.0 4.0.0 > $TRAVIS_BUILD_DIR/upgrade390400-3.log
          php upgrade.php 4.0.0 5.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade400500.log
          php upgrade2.php 4.0.0 5.0.0 > $TRAVIS_BUILD_DIR/upgrade400500-2.log
          php step5.php 4.0.0 5.0.0 > $TRAVIS_BUILD_DIR/upgrade400500-3.log
          php upgrade.php 5.0.0 6.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade500600.log
          php upgrade2.php 5.0.0 6.0.0 > $TRAVIS_BUILD_DIR/upgrade500600-2.log
          php step5.php 5.0.0 6.0.0 > $TRAVIS_BUILD_DIR/upgrade500600-3.log
          php upgrade.php 6.0.0 7.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade600700.log
          php upgrade2.php 6.0.0 7.0.0 > $TRAVIS_BUILD_DIR/upgrade600700-2.log
          php step5.php 6.0.0 7.0.0 > $TRAVIS_BUILD_DIR/upgrade600700-3.log
          php upgrade.php 7.0.0 8.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade700800.log
          php upgrade2.php 7.0.0 8.0.0 > $TRAVIS_BUILD_DIR/upgrade700800-2.log
          php step5.php 7.0.0 8.0.0 > $TRAVIS_BUILD_DIR/upgrade700800-3.log
          php upgrade.php 8.0.0 9.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade800900.log
          php upgrade2.php 8.0.0 9.0.0 > $TRAVIS_BUILD_DIR/upgrade800900-2.log
          php step5.php 8.0.0 9.0.0 > $TRAVIS_BUILD_DIR/upgrade800900-3.log
          php upgrade.php 9.0.0 10.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade9001000.log
          php upgrade2.php 9.0.0 10.0.0 > $TRAVIS_BUILD_DIR/upgrade9001000-2.log
          php step5.php 9.0.0 10.0.0 > $TRAVIS_BUILD_DIR/upgrade9001000-3.log
          php upgrade.php 10.0.0 11.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade10001100.log
          php upgrade2.php 10.0.0 11.0.0 > $TRAVIS_BUILD_DIR/upgrade10001100-2.log
          php step5.php 10.0.0 11.0.0 > $TRAVIS_BUILD_DIR/upgrade10001100-3.log
          php upgrade.php 11.0.0 12.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade11001200.log
          php upgrade2.php 11.0.0 12.0.0 > $TRAVIS_BUILD_DIR/upgrade11001200-2.log
          php step5.php 11.0.0 12.0.0 > $TRAVIS_BUILD_DIR/upgrade11001200-3.log
          php upgrade.php 12.0.0 13.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade12001300.log
          php upgrade2.php 12.0.0 13.0.0 > $TRAVIS_BUILD_DIR/upgrade12001300-2.log
          php step5.php 12.0.0 13.0.0 > $TRAVIS_BUILD_DIR/upgrade12001300-3.log
          php upgrade.php 13.0.0 14.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade13001400.log
          php upgrade2.php 13.0.0 14.0.0 > $TRAVIS_BUILD_DIR/upgrade13001400-2.log
          php step5.php 13.0.0 14.0.0 > $TRAVIS_BUILD_DIR/upgrade13001400-3.log
          php upgrade.php 14.0.0 15.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade14001500.log
          php upgrade2.php 14.0.0 15.0.0 > $TRAVIS_BUILD_DIR/upgrade14001500-2.log
          php step5.php 14.0.0 15.0.0 > $TRAVIS_BUILD_DIR/upgrade14001500-3.log
          php upgrade.php 15.0.0 16.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade15001600.log
          php upgrade2.php 15.0.0 16.0.0 > $TRAVIS_BUILD_DIR/upgrade15001600-2.log
          php step5.php 15.0.0 16.0.0 > $TRAVIS_BUILD_DIR/upgrade15001600-3.log
          php upgrade.php 16.0.0 17.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade16001700.log
          php upgrade2.php 16.0.0 17.0.0 > $TRAVIS_BUILD_DIR/upgrade16001700-2.log
          php step5.php 16.0.0 17.0.0 > $TRAVIS_BUILD_DIR/upgrade16001700-3.log
          php upgrade.php 17.0.0 18.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade17001800.log
          php upgrade2.php 17.0.0 18.0.0 > $TRAVIS_BUILD_DIR/upgrade17001800-2.log
          php step5.php 17.0.0 18.0.0 > $TRAVIS_BUILD_DIR/upgrade17001800-3.log
          php upgrade.php 18.0.0 19.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade18001900.log || cat $TRAVIS_BUILD_DIR/upgrade18001900.log
          php upgrade2.php 18.0.0 19.0.0 > $TRAVIS_BUILD_DIR/upgrade18001900-2.log || cat $TRAVIS_BUILD_DIR/upgrade18001900-2.log
          php step5.php 18.0.0 19.0.0 > $TRAVIS_BUILD_DIR/upgrade18001900-3.log || cat $TRAVIS_BUILD_DIR/upgrade18001900-3.log
          php upgrade.php 19.0.0 20.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade19002000.log || cat $TRAVIS_BUILD_DIR/upgrade19002000.log
          php upgrade2.php 19.0.0 20.0.0 > $TRAVIS_BUILD_DIR/upgrade19002000-2.log || cat $TRAVIS_BUILD_DIR/upgrade19002000-2.log
          php step5.php 19.0.0 20.0.0 > $TRAVIS_BUILD_DIR/upgrade19002000-3.log || cat $TRAVIS_BUILD_DIR/upgrade19002000-3.log
          php upgrade.php 20.0.0 21.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade20002100.log || cat $TRAVIS_BUILD_DIR/upgrade20002100.log
          php upgrade2.php 20.0.0 21.0.0 > $TRAVIS_BUILD_DIR/upgrade20002100-2.log || cat $TRAVIS_BUILD_DIR/upgrade20002100-2.log
          php step5.php 20.0.0 21.0.0 > $TRAVIS_BUILD_DIR/upgrade20002100-3.log || cat $TRAVIS_BUILD_DIR/upgrade20002100-3.log
          php upgrade.php 21.0.0 22.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade21002200.log || cat $TRAVIS_BUILD_DIR/upgrade21002200.log
          php upgrade2.php 21.0.0 22.0.0 > $TRAVIS_BUILD_DIR/upgrade21002200-2.log || cat $TRAVIS_BUILD_DIR/upgrade21002200-2.log
          php step5.php 21.0.0 22.0.0 > $TRAVIS_BUILD_DIR/upgrade21002200-3.log || cat $TRAVIS_BUILD_DIR/upgrade21002200-3.log
          php upgrade.php 22.0.0 23.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade22002300.log || cat $TRAVIS_BUILD_DIR/upgrade22002300.log
          php upgrade2.php 22.0.0 23.0.0 > $TRAVIS_BUILD_DIR/upgrade22002300-2.log || cat $TRAVIS_BUILD_DIR/upgrade22002300-2.log
          php step5.php 22.0.0 23.0.0 > $TRAVIS_BUILD_DIR/upgrade22002300-3.log || cat $TRAVIS_BUILD_DIR/upgrade22002300-3.log
          set +e

      - name: Enable modules
        run: |
          set -e
          cd htdocs/install
          php upgrade2.php 0.0.0 0.0.0 MAIN_MODULE_API,MAIN_MODULE_ProductBatch,MAIN_MODULE_SupplierProposal,MAIN_MODULE_STRIPE,MAIN_MODULE_ExpenseReport > $TRAVIS_BUILD_DIR/enablemodule.log
          php upgrade2.php 0.0.0 0.0.0 MAIN_MODULE_WEBSITE,MAIN_MODULE_TICKET,MAIN_MODULE_ACCOUNTING,MAIN_MODULE_MRP >> $TRAVIS_BUILD_DIR/enablemodule.log
          php upgrade2.php 0.0.0 0.0.0 MAIN_MODULE_RECEPTION,MAIN_MODULE_RECRUITMENT >> $TRAVIS_BUILD_DIR/enablemodule.log
          php upgrade2.php 0.0.0 0.0.0 MAIN_MODULE_KnowledgeManagement,MAIN_MODULE_EventOrganization,MAIN_MODULE_PARTNERSHIP >> $TRAVIS_BUILD_DIR/enablemodule.log
          php upgrade2.php 0.0.0 0.0.0 MAIN_MODULE_EmailCollector >> $TRAVIS_BUILD_DIR/enablemodule.log
          cd -
          set +e
          cat $TRAVIS_BUILD_DIR/enablemodule.log || true

      - name: PHPUnit
        run: |
          phpunit -d memory_limit=-1 -c test/phpunit/phpunittest.xml test/phpunit/AllTests.php | tee /dev/tty | grep -qE "(OK .*[0-9]+ tests.*[0-9]+ assertions|Tests: [0-9]+)" ; phpunitresult=$((PIPESTATUS[0]?PIPESTATUS[0]:PIPESTATUS[2]))
          echo "Phpunit return code = $phpunitresult"
          [ $phpunitresult == 0 ] || exit $phpunitresult

      - name: After script (logs)
        if: ${{ always() }}
        run: |
          echo "After script - Output last lines of dolibarr.log"
          ls "$TRAVIS_BUILD_DIR/documents" || true
          sudo tail -n 50 "$TRAVIS_BUILD_DIR/documents/dolibarr.log" || true
          echo "After script - Output last lines of apache error.log"
          sudo ls /var/log/apache2 || true
          sudo tail -n 200 /var/log/apache2/travis_error_log || sudo tail -n 200 /var/log/apache2/error.log || true
